name: Build

on:
  pull_request:
  push:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Clean node_modules and Nx cache
        run: |
          rm -rf node_modules
          rm -rf .nx/cache

      - name: Install dependencies
        run: npm ci

      - name: Build types library
        run: npx nx build types --skip-nx-cache

      - name: Build frontend
        run: npx nx build apps/frontend --skip-nx-cache

      - name: Build backend
        run: npx nx run backend:build --with-deps --skip-nx-cache
