name: Docker Compose CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:  # para ejecutar manualmente

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout del repo
      - uses: actions/checkout@v6

      # 2) Logueo en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3) Instalar Docker Compose si no est√°
      - name: Set up Docker Compose
        run: |
          docker-compose version || sudo apt-get update && sudo apt-get install -y docker-compose

      # 4) Build & push usando docker-compose
      - name: Build & Push Docker images
        run: |
          docker-compose -f docker-compose.yml build
          docker-compose -f docker-compose.yml push
