#name: Test
#
#on:
#  pull_request:
#  push:
#    branches: [ master, develop ]
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Setup Node
#        uses: actions/setup-node@v4
#        with:
#          node-version: 20
#          cache: npm
#
#      - name: Restore Nx cache
#        uses: actions/cache@v4
#        with:
#          path: .nx/cache
#          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
#          restore-keys: |
#            ${{ runner.os }}-nx-
#
#      - name: Install dependencies
#        run: npm ci
#
#      - name: Run frontend tests
#        run: npx nx test apps/frontend --skip-nx-cache
#
#      - name: Run backend tests
#        run: npx nx test apps/backend --skip-nx-cache
#
#      - name: Save Nx cache
#        uses: actions/cache@v4
#        with:
#          path: .nx/cache
#          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
